name: OreMarket
version: ${project.version}
main: me.olliejw.oremarket.OreMarket
api-version: 1.16
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]
authors: [ OllieJW ]
description: Realistic stock market for ores
website: https://olliejw.me

commands:
  openmarket:
    description: Opens OreMarket GUI
    usage: /<command>
  om-reload:
    description: Reloads OreMarket
    usage: /<command>
  om-stats:
    description: Shows OreMarket stats
    usage: /<command>
  om-crash:
    description: Crashes Market
    usage: /<command>

permissions:
  oremarket.crashmarket:
    default: op
  oremarket.reload:
    default: op
  oremarket.open:
    default: not op
  oremarket.stats:
    default: not op